/*!
Pug compile for webpack

https://github.com/io-arc/io-arc/tasks/tasks-webpack-pug
Version: 0.0.0
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,a){"object"==typeof exports&&"undefined"!=typeof module?a(exports,require("@io-arc/env"),require("@io-arc/file-list"),require("@io-arc/utils"),require("@io-arc/read-yaml"),require("@io-arc/webpack-loaders-image"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/webpack-settings"),require("@io-arc/webpack-loaders-pug-linter")):"function"==typeof define&&define.amd?define(["exports","@io-arc/env","@io-arc/file-list","@io-arc/utils","@io-arc/read-yaml","@io-arc/webpack-loaders-image","@io-arc/webpack-plugins-task-message","@io-arc/webpack-settings","@io-arc/webpack-loaders-pug-linter"],a):a((e=e||self).html={},e.env,e.fileList,e.utils,e.readYaml,e.webpackLoadersImage,e.TaskMessage,e.webpackSettings,e.webpackLoadersPugLinter)}(this,(function(e,a,t,r,i,s,o,l,p){"use strict";o=o&&Object.prototype.hasOwnProperty.call(o,"default")?o.default:o;const c=require("pug-php-filter"),u=require("extract-text-webpack-plugin"),T=require("progress-bar-webpack-plugin"),_={loader:"html-loader",options:{attributes:!!a.USE_HTML_FILE_LOADER&&{list:a.TARGET_HTML_FILE_LOADER}}},n={loader:"pug-html-loader",options:{doctype:"html",pretty:!a.HTML_MINIFY,cache:!0,filters:{php:c},data:{IS_PRODUCTION:a.IS_PRODUCTION,TITLE:a.SITE_TITLE,URL:a.SITE_URL,AUTHOR:a.SITE_AUTHOR,DESCRIPTION:a.SITE_DESCRIPTION,SITE_ROOT:a.SITE_ROOT,CSS_DIR:r.AssetsDirPath(a.OUTPUT_CSS_ARRAY),IMG_DIR:r.AssetsDirPath(a.OUTPUT_IMG_ARRAY),JS_DIR:r.AssetsDirPath(a.OUTPUT_JS_ARRAY),JSON_DIR:r.AssetsDirPath(a.OUTPUT_JSON_ARRAY),readYAML:e=>{const t=e.split("/"),r=t.pop();if(void 0===r||!/ya?ml$/i.test(r))return"";const s=r.replace(/.ya?ml$/i,"");return i.ReadYaml(s,[a.WS_HTML_PATH_ABSOLUTE,...t])}}}},d=a.OUTPUT_IN_PHP?"php":"html",I={mode:a.NODE_ENV,context:a.WS_HTML_PATH_ABSOLUTE,watch:a.MODE_ENV===a.MODE.WATCH,entry:()=>new Promise(e=>{e(t.FileListObject(a.WS_HTML_PATH_ABSOLUTE,"pug"))}),output:{path:a.DIST_ABSOLUTE,publicPath:"",filename:`[name].${d}`},module:{rules:[p.PugLintLoader(/^(?!_).*\.pug$/i,"pug-lint-loader"),{test:/\.pug$/i,use:u.extract({fallback:"",publicPath:a.DIST,use:[_,n]})},s.ImageLoader([],a.OUTPUT_IMG_ARRAY,a.IS_HASH_HTML_FILE_LOADER)]},plugins:[new o("pug"),new u({filename:`[name].${d}`,disable:!1,allChunks:!0}),new T(l.progressBar("pug"))],devtool:!1,cache:!0,stats:l.stats(),performance:l.performance()};e.html=I,Object.defineProperty(e,"__esModule",{value:!0})}));
