/*!
CSS build for webpack

https://github.com/io-arc/io-arc/tasks/tasks-webpack-css
Version: 0.0.0
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,s){"object"==typeof exports&&"undefined"!=typeof module?s(exports,require("@io-arc/env"),require("@io-arc/file-list"),require("@io-arc/webpack-loaders-image"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/webpack-settings")):"function"==typeof define&&define.amd?define(["exports","@io-arc/env","@io-arc/file-list","@io-arc/webpack-loaders-image","@io-arc/webpack-plugins-task-message","@io-arc/webpack-settings"],s):s((e=e||self).html={},e.env,e.fileList,e.webpackLoadersImage,e.TaskMessage,e.webpackSettings)}(this,(function(e,s,r,o,a,i){"use strict";a=a&&Object.prototype.hasOwnProperty.call(a,"default")?a.default:a;const t=require("mini-css-extract-plugin"),c=require("webpack-fix-style-only-entries"),n=require("optimize-css-assets-webpack-plugin"),p=require("progress-bar-webpack-plugin"),l=require("postcss-safe-parser"),u={loader:"css-loader",options:{url:s.USE_CSS_FILE_LOADER,sourceMap:!1,import:!0}},d={loader:t.loader,options:{hmr:!1}},m=require("autoprefixer"),_=require("css-mqpacker"),f={loader:"postcss-loader",options:{sourceMap:!1,plugins:()=>[m({grid:"autoplace",flexbox:"no-2009"}),_()]}},S=[];s.CSS_MINIFY&&S.push(new n({cssProcessorOptions:{parser:l,discardComments:{removeAll:!0}}}));const g={mode:s.NODE_ENV,context:s.WS_CSS_PATH_ABSOLUTE,watch:s.MODE_ENV===s.MODE.WATCH,entry:()=>new Promise(e=>{e(r.FileListObject(s.WS_CSS_PATH_ABSOLUTE,"css"))}),output:{path:s.OUTPUT_CSS_PATH_ABSOLUTE},module:{rules:[{test:/\.css$/,exclude:/node_modules/,use:[d,u,{loader:"resolve-url-loader",options:{sourceMap:!1,keepQuery:!0}},f]},o.ImageLoader(s.OUTPUT_CSS_ARRAY,s.OUTPUT_IMG_ARRAY,s.IS_HASH_CSS_FILE_LOADER)]},plugins:[new a("css"),new c({extensions:["css"]}),new t({filename:"[name].css",chunkFilename:"[id].css"}),new p(i.progressBar("css")),...S],devtool:!1,cache:!0,stats:i.stats(),performance:i.performance()};e.css=g,Object.defineProperty(e,"__esModule",{value:!0})}));
