root: true

parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  allowImportExportEverywhere: false
  ecmaFeatures:
    globalReturn: false
  babelOptions:
    configFile: .babelrc

env:
  browser: true
  es6: true
  worker: true
  node: true

extends:
  - standard
  - plugin:prettier/recommended

plugins:
  - babel

rules:
  no-mixed-spaces-and-tabs: error
  eol-last: off
  no-unused-vars: warn
  semi: off

  space-before-function-paren: off

  prettier/prettier:
    - error
    - trailingComma: none
      tabWidth: 2
      singleQuote: true
      semi: false
      arrowParens: always

  eofline: off

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  IS_PRODUCTION: readonly
  TITLE: readonly
  URL: readonly
  AUTHOR: readonly
  SITE_ROOT: readonly
