/*!
Babel compile for webpack

https://github.com/io-arc/io-arc/tree/master/tasks/task-webpack-babel
Version: 0.2.6
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,a){"object"==typeof exports&&"undefined"!=typeof module?a(exports,require("@io-arc/utils"),require("@io-arc/webpack-loaders-js"),require("@io-arc/env"),require("@io-arc/webpack-loaders-image"),require("webpack"),require("@io-arc/file-list"),require("@io-arc/path-build"),require("@io-arc/webpack-settings"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/output-dir-diff")):"function"==typeof define&&define.amd?define(["exports","@io-arc/utils","@io-arc/webpack-loaders-js","@io-arc/env","@io-arc/webpack-loaders-image","webpack","@io-arc/file-list","@io-arc/path-build","@io-arc/webpack-settings","@io-arc/webpack-plugins-task-message","@io-arc/output-dir-diff"],a):a((e="undefined"!=typeof globalThis?globalThis:e||self).BuildWebpackBabel={},e.utils,e.webpackLoadersJs,e.env,e.webpackLoadersImage,e.webpack,e.fileList,e.PathBuild,e.webpackSettings,e.TaskMessage,e.OutputDirDiff)}(this,(function(e,a,r,t,i,s,o,l,n,c,p){"use strict";s=s&&Object.prototype.hasOwnProperty.call(s,"default")?s.default:s,l=l&&Object.prototype.hasOwnProperty.call(l,"default")?l.default:l,c=c&&Object.prototype.hasOwnProperty.call(c,"default")?c.default:c,p=p&&Object.prototype.hasOwnProperty.call(p,"default")?p.default:p;const u=[r.babelLoader];t.USE_JS_FILE_LOADER&&u.push(i.ImageLoader(t.OUTPUT_JS_ARRAY,t.OUTPUT_IMG_ARRAY,t.IS_HASH_JS_FILE_LOADER));const d=[];if(t.JS_MINIFY){const e=require("terser-webpack-plugin");d.push(new e({parallel:!0,terserOptions:{extractComments:"all",compress:{drop_console:!0}}}))}if(t.MODE_ENV===t.MODE.ONCE){const e=new p([t.DIST,...t.OUTPUT_JS_ARRAY],[]),a=require("webpack-visualizer-plugin");d.push(new a({filename:e.targetRelativePath()+"stats/index.html"}))}const b=require("progress-bar-webpack-plugin"),f=require("prettier-webpack-plugin"),w=require("config-webpack"),_=new a.WebpackExtend("js"),O=_.externals(),k=_.loaders();null!=k&&u.push(...k);const S={mode:"none",entry:()=>new Promise(e=>{e({...o.FileListObject(t.WS_JS_PATH_ABSOLUTE,"js",!0),...o.FileListObject(t.WS_JS_PATH_ABSOLUTE,"jsx",!0)})}),output:{path:t.OUTPUT_JS_PATH_ABSOLUTE,filename:"[name].js",publicPath:l.relative(t.OUTPUT_JS_ARRAY),chunkFilename:"[name].js"},optimization:n.jsSplitChunks,externals:O,resolve:{extensions:[".js",".jsx",".json"],alias:{"~":t.WS_ROOT_ABSOLUTE,"@":t.WS_ROOT_ABSOLUTE}},module:{exprContextCritical:!1,rules:[r.workerLoader,...u,r.yamlLoader,r.EslintLoader(t.ESLINT)]},plugins:[new c("Babel"),new s.DefinePlugin(n.webpackDefine),new b(n.progressBar("Babel")),new f({extensions:[".js",".jsx",".yaml",".json"]}),new w,...d],devtool:!!t.JS_SOURCE_MAP&&"source-map",cache:!0,stats:n.stats(),performance:n.performance()};e.js=S,Object.defineProperty(e,"__esModule",{value:!0})}));
