/*!
@io-arc/task-webpack-babel
Babel compile for webpack

Version: 0.4.0
License: ISC

Repository: https://github.com/io-arc/io-arc
Documents: https://github.com/io-arc/io-arc/tree/master/tasks/task-webpack-babel

Copyright (c) 2020-2021 arc one
*/
!function(e,a){"object"==typeof exports&&"undefined"!=typeof module?a(exports,require("@io-arc/env"),require("@io-arc/file-list"),require("@io-arc/output-dir-diff"),require("@io-arc/path-build"),require("@io-arc/utils"),require("@io-arc/webpack-loaders-image"),require("@io-arc/webpack-loaders-js"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/webpack-settings"),require("webpack")):"function"==typeof define&&define.amd?define(["exports","@io-arc/env","@io-arc/file-list","@io-arc/output-dir-diff","@io-arc/path-build","@io-arc/utils","@io-arc/webpack-loaders-image","@io-arc/webpack-loaders-js","@io-arc/webpack-plugins-task-message","@io-arc/webpack-settings","webpack"],a):a((e="undefined"!=typeof globalThis?globalThis:e||self).BuildWebpackBabel={},e.env,e.fileList,e.OutputDirDiff,e.PathBuild,e.utils,e.webpackLoadersImage,e.webpackLoadersJs,e.TaskMessage,e.webpackSettings,e.webpack)}(this,(function(e,a,i,t,r,s,o,l,n,c,p){"use strict";t=t&&Object.prototype.hasOwnProperty.call(t,"default")?t.default:t,r=r&&Object.prototype.hasOwnProperty.call(r,"default")?r.default:r,n=n&&Object.prototype.hasOwnProperty.call(n,"default")?n.default:n,p=p&&Object.prototype.hasOwnProperty.call(p,"default")?p.default:p;const u=[l.babelLoader];a.USE_JS_FILE_LOADER&&u.push(o.ImageLoader(a.OUTPUT_JS_ARRAY,a.OUTPUT_IMG_ARRAY,a.IS_HASH_JS_FILE_LOADER));const d=[];if(d.push(o.ImageMinPlugin),a.MODE_ENV===a.MODE.ONCE){const e=new t([a.DIST,...a.OUTPUT_JS_ARRAY],[]),i=require("webpack-visualizer-plugin");d.push(new i({filename:e.targetRelativePath()+"stats/index.html"}))}const b=require("progress-bar-webpack-plugin"),f=require("prettier-webpack-plugin"),w=require("config-webpack"),O=new s.WebpackExtends("js"),_=O.externals(),g=O.loaders();null!=g&&u.push(...g);const k=O.plugins();null!=k&&d.push(...k);const m={mode:"none",entry:()=>new Promise(e=>{e({...i.FileListObject(a.WS_JS_PATH_ABSOLUTE,"js",!0),...i.FileListObject(a.WS_JS_PATH_ABSOLUTE,"jsx",!0)})}),output:{path:a.OUTPUT_JS_PATH_ABSOLUTE,filename:"[name].js",publicPath:r.relative(a.OUTPUT_JS_ARRAY),chunkFilename:"[name].js"},optimization:c.jsOptimization,externals:_,resolve:{extensions:[".js",".jsx",".json"],alias:{"~":a.WS_ROOT_ABSOLUTE,"@":a.WS_ROOT_ABSOLUTE}},module:{exprContextCritical:!1,rules:[l.workerLoader,...u,l.yamlLoader,l.EslintLoader(a.ESLINT)]},plugins:[new n("Babel"),new p.DefinePlugin(c.webpackDefine),new b(c.progressBar("Babel")),new f({extensions:[".js",".jsx",".yaml",".json"]}),new w,...d],devtool:!!a.JS_SOURCE_MAP&&"source-map",cache:!0,stats:c.stats(),performance:c.performance()};e.js=m,Object.defineProperty(e,"__esModule",{value:!0})}));
