/*!
HTML builds for webpack

https://github.com/io-arc/io-arc/tasks/task-webpack-html
Version: 0.0.0
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("@io-arc/env"),require("@io-arc/file-list"),require("@io-arc/webpack-loaders-image"),require("@io-arc/webpack-settings"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/utils"),require("handlebars")):"function"==typeof define&&define.amd?define(["exports","@io-arc/env","@io-arc/file-list","@io-arc/webpack-loaders-image","@io-arc/webpack-settings","@io-arc/webpack-plugins-task-message","@io-arc/utils","handlebars"],t):t((e=e||self).BuildWebpackHtml={},e.env,e.fileList,e.webpackLoadersImage,e.webpackSettings,e.TaskMessage,e.utils,e.handlebars)}(this,(function(e,t,a,r,s,i,l,o){"use strict";i=i&&Object.prototype.hasOwnProperty.call(i,"default")?i.default:i,o=o&&Object.prototype.hasOwnProperty.call(o,"default")?o.default:o;const c=require("extract-text-webpack-plugin"),n=require("progress-bar-webpack-plugin"),T={mode:t.NODE_ENV,context:t.WS_HTML_PATH_ABSOLUTE,watch:t.MODE_ENV===t.MODE.WATCH,entry:()=>new Promise(e=>{e(a.FileListObject(t.WS_HTML_PATH_ABSOLUTE,"html"))}),output:{path:t.DIST_ABSOLUTE,publicPath:"",filename:"[name].html"},module:{rules:[{test:/\.html$/i,use:c.extract({fallback:"",publicPath:t.DIST,use:[{loader:"html-loader",options:{attributes:!!t.USE_HTML_FILE_LOADER&&{list:t.TARGET_HTML_FILE_LOADER},minimize:t.HTML_MINIFY,preprocessor:(e,a)=>{let r;try{r=o.compile(e)({IS_PRODUCTION:t.IS_PRODUCTION,TITLE:t.SITE_TITLE,URL:t.SITE_URL,AUTHOR:t.SITE_AUTHOR,DESCRIPTION:t.SITE_DESCRIPTION,SITE_ROOT:t.SITE_ROOT,CSS_DIR:l.AssetsDirPath(t.OUTPUT_CSS_ARRAY),IMG_DIR:l.AssetsDirPath(t.OUTPUT_IMG_ARRAY),JS_DIR:l.AssetsDirPath(t.OUTPUT_JS_ARRAY),JSON_DIR:l.AssetsDirPath(t.OUTPUT_JSON_ARRAY)})}catch(t){return a.emitError(t),e}return r}}}]})},r.ImageLoader([],t.OUTPUT_IMG_ARRAY,t.IS_HASH_HTML_FILE_LOADER)]},plugins:[new i("html"),new c({filename:"[name].html",disable:!1,allChunks:!0}),new n(s.progressBar("html"))],devtool:!1,cache:!0,stats:s.stats(),performance:s.performance()};e.html=T,Object.defineProperty(e,"__esModule",{value:!0})}));
