/*!
TypeScript compile for webpack

https://github.com/io-arc/io-arc/tasks/tasks-webpack-typescript
Version: 0.0.0
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("@io-arc/env"),require("@io-arc/webpack-loaders-image"),require("webpack"),require("@io-arc/file-list"),require("@io-arc/path-build"),require("@io-arc/webpack-settings"),require("@io-arc/webpack-loaders-js"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/output-dir-diff")):"function"==typeof define&&define.amd?define(["exports","@io-arc/env","@io-arc/webpack-loaders-image","webpack","@io-arc/file-list","@io-arc/path-build","@io-arc/webpack-settings","@io-arc/webpack-loaders-js","@io-arc/webpack-plugins-task-message","@io-arc/output-dir-diff"],t):t((e=e||self).html={},e.env,e.webpackLoadersImage,e.webpack,e.fileList,e.PathBuild,e.webpackSettings,e.webpackLoadersJs,e.TaskMessage,e.OutputDirDiff)}(this,(function(e,t,r,a,i,s,o,p,c,n){"use strict";a=a&&Object.prototype.hasOwnProperty.call(a,"default")?a.default:a,s=s&&Object.prototype.hasOwnProperty.call(s,"default")?s.default:s,c=c&&Object.prototype.hasOwnProperty.call(c,"default")?c.default:c,n=n&&Object.prototype.hasOwnProperty.call(n,"default")?n.default:n;const l=require("progress-bar-webpack-plugin"),u=require("terser-webpack-plugin"),d=require("prettier-webpack-plugin"),f=require("webpack-visualizer-plugin"),_=[p.TypescriptLoader()];t.USE_JS_FILE_LOADER&&_.push(r.ImageLoader(t.OUTPUT_JS_ARRAY,t.OUTPUT_IMG_ARRAY,t.IS_HASH_JS_FILE_LOADER));const w=[];if(t.JS_MINIFY&&w.push(new u({parallel:!0,terserOptions:{extractComments:"all",compress:{drop_console:!0}}})),t.MODE_ENV===t.MODE.ONCE){const e=new n([t.DIST,...t.OUTPUT_JS_ARRAY],[]);w.push(new f({filename:e.targetRelativePath()+"stats/index.html"}))}const O={mode:"none",context:t.WS_JS_PATH_ABSOLUTE,entry:()=>new Promise(e=>{e(i.FileListObject(t.WS_JS_PATH_ABSOLUTE,"t[s,sx]",!0))}),output:{path:t.OUTPUT_JS_PATH_ABSOLUTE,filename:"[name].js",publicPath:s.relative(t.OUTPUT_JS_ARRAY),chunkFilename:"[name].js"},optimization:o.jsSplitChunks,resolve:{extensions:[".ts",".tsx",".js",".json"],alias:{"~":t.WS_ROOT_ABSOLUTE,"@":t.WS_ROOT_ABSOLUTE}},module:{exprContextCritical:!1,rules:[p.workerLoader,..._,p.yamlLoader,p.EslintLoader()]},plugins:[new c("TypeScript"),new a.DefinePlugin(o.webpackDefine),new l(o.progressBar("TypeScript")),new d({extensions:[".js",".jsx",".ts",".tsx",".yaml",".yml"]}),...w],devtool:!!t.JS_SOURCE_MAP&&"source-map",cache:!0,stats:o.stats(),performance:o.performance()};e.js=O,Object.defineProperty(e,"__esModule",{value:!0})}));
