/*!
Run BrowserSync

https://github.com/io-arc/io-arc/tasks/task-browser-sync
Version: 0.0.0
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,r){"object"==typeof exports&&"undefined"!=typeof module?r(require("commander"),require("fs"),require("@io-arc/read-yaml"),require("rxjs"),require("rxjs/operators"),require("@io-arc/env"),require("browser-sync")):"function"==typeof define&&define.amd?define(["commander","fs","@io-arc/read-yaml","rxjs","rxjs/operators","@io-arc/env","browser-sync"],r):r((e=e||self).commander,e.fs,e.readYaml,e.rxjs,e.operators,e.env,e.browserSync)}(this,(function(e,r,t,s,i,o,a){"use strict";r=r&&Object.prototype.hasOwnProperty.call(r,"default")?r.default:r,a=a&&Object.prototype.hasOwnProperty.call(a,"default")?a.default:a;var n,c,d,p,h,l=function(e,r,t){if(!r.has(e))throw new TypeError("attempted to set private field on non-instance");return r.set(e,t),t},u=function(e,r){if(!r.has(e))throw new TypeError("attempted to get private field on non-instance");return r.get(e)};class f{constructor(e,t){n.set(this,void 0),c.set(this,void 0),d.set(this,void 0),p.set(this,e=>{try{return r.statSync(`${process.cwd()}/config/${e}`),e}catch(e){return}}),h.set(this,e=>s.of(e).pipe(i.map(e=>(void 0!==e.files||(e.files=`${o.DIST}/**/*`),e)),i.map(e=>void 0!==u(this,n)||void 0!==e.proxy?(void 0!==e.server&&delete e.server,void 0!==u(this,n)&&(e.proxy=u(this,n)),e):(void 0===e.server&&(e.server=`${o.DIST}/`),e)),i.map(e=>{if(void 0!==e.serveStatic)return e;const r=o.SITE_ROOT.replace(/\/$/,"");return""!==r&&(e.serveStatic=[{route:[r],dir:o.DIST}]),e}),i.map(e=>{if(void 0===u(this,c))return e;const r=require("connect-history-api-fallback")({index:u(this,c)});return e.middleware=[...r],e.single=!0,e}))),l(this,n,e),l(this,c,t),l(this,d,u(this,p).call(this,"browser-sync.yml")),void 0===u(this,d)&&(l(this,d,u(this,p).call(this,"browser-sync.yaml")),void 0===u(this,d)&&(l(this,d,u(this,p).call(this,"bs.yml")),void 0===u(this,d)&&l(this,d,u(this,p).call(this,"bs.yaml"))))}run(){const e=u(this,d)?t.ReadYaml(u(this,d),["config"]):{};u(this,h).call(this,e).subscribe(e=>{a(e)})}}n=new WeakMap,c=new WeakMap,d=new WeakMap,p=new WeakMap,h=new WeakMap,(()=>{e.program.version("0.0.0").option("-p, --proxy <ip-address>","Proxy server address").option("--history <filepath>","File paths used by the HTML5 HistoryAPI (e.g. /index.html)").parse(process.argv);const r=e.program.proxy||void 0,t=e.program.history||void 0;new f(r,t).run()})()}));
