# Build settings

# build output
outputDir: dist

# working directory
wsDir:
  static: static
  yaml2json: yaml2json
  img: img

# directory configuration
# array is hierarchy
deployDir:
  json: [common, data]
  img: [common, img]

# build option
options:
  json:
    minify: true
