# Build settings

# build output
outputDir: dist

# working directory
wsDir:
  static: static
  html: html
  yaml2json: yaml2json
  img: img

# directory configuration
# array is hierarchy
deployDir:
  json: [common, data]
  img: [common, img]
  css: [common, css]
  js: [common, js]

# build option
options:
  html:
    minify: false

  json:
    minify: true

  # use file-loader
  fileLoader:
    html:
      use: true
      hash: true
      target:
        - tag: img
          attribute: src
          type: src
        - tag: img
          attribute: srcset
          type: srcset
        - tag: img
          attribute: data-src
          type: src
        - tag: img
          attribute: data-srcset
          type: srcset
        - tag: source
          attribute: src
          type: src
