/*!
Stylus compile for webpack

https://github.com/io-arc/io-arc/tree/master/tasks/tasks-webpack-stylus
Version: 0.2.6
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,s){"object"==typeof exports&&"undefined"!=typeof module?s(exports,require("@io-arc/env"),require("@io-arc/file-list"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/webpack-settings"),require("@io-arc/webpack-loaders-image")):"function"==typeof define&&define.amd?define(["exports","@io-arc/env","@io-arc/file-list","@io-arc/webpack-plugins-task-message","@io-arc/webpack-settings","@io-arc/webpack-loaders-image"],s):s((e="undefined"!=typeof globalThis?globalThis:e||self).BuildWebpackStylus={},e.env,e.fileList,e.TaskMessage,e.webpackSettings,e.webpackLoadersImage)}(this,(function(e,s,r,o,a,i){"use strict";o=o&&Object.prototype.hasOwnProperty.call(o,"default")?o.default:o;const t={loader:"css-loader",options:{url:s.USE_CSS_FILE_LOADER,sourceMap:!1,import:!0}},c=require("mini-css-extract-plugin"),l={loader:c.loader,options:{hmr:!1}},n=require("autoprefixer"),p=require("css-mqpacker"),u={loader:"postcss-loader",options:{sourceMap:!1,plugins:()=>[n({grid:"autoplace",flexbox:"no-2009"}),p()]}},d=[];if(s.CSS_MINIFY){const e=require("optimize-css-assets-webpack-plugin"),s=require("postcss-safe-parser");d.push(new e({cssProcessorOptions:{parser:s,discardComments:{removeAll:!0}}}))}const f=require("webpack-fix-style-only-entries"),_=require("progress-bar-webpack-plugin"),m={mode:s.NODE_ENV,context:s.WS_CSS_PATH_ABSOLUTE,watch:s.MODE_ENV===s.MODE.WATCH,entry:()=>new Promise(e=>{e(r.FileListObject(s.WS_CSS_PATH_ABSOLUTE,"styl"))}),output:{path:s.OUTPUT_CSS_PATH_ABSOLUTE},module:{rules:[{test:/\.styl$/,exclude:/node_modules/,use:[l,t,{loader:"resolve-url-loader",options:{sourceMap:!1,keepQuery:!0}},u,{loader:"stylus-loader",options:{sourceMap:!1,"include css":!0,define:null}}]},i.ImageLoader(s.OUTPUT_CSS_ARRAY,s.OUTPUT_IMG_ARRAY,s.IS_HASH_CSS_FILE_LOADER)]},plugins:[new o("stylus"),new f({extensions:["styl","css"]}),new c({filename:"[name].css",chunkFilename:"[id].css"}),new _(a.progressBar("stylus")),...d],devtool:!1,cache:!0,stats:a.stats(),performance:a.performance()};e.css=m,Object.defineProperty(e,"__esModule",{value:!0})}));
