/*!
Stylus compile for webpack

https://github.com/io-arc/io-arc/tree/master/tasks/tasks-webpack-stylus
Version: 0.4.0
License: ISC
Copyright (c) 2020 arc one
*/
!function(e,s){"object"==typeof exports&&"undefined"!=typeof module?s(exports,require("@io-arc/utils"),require("@io-arc/env"),require("@io-arc/file-list"),require("@io-arc/webpack-plugins-task-message"),require("@io-arc/webpack-settings"),require("@io-arc/webpack-loaders-image")):"function"==typeof define&&define.amd?define(["exports","@io-arc/utils","@io-arc/env","@io-arc/file-list","@io-arc/webpack-plugins-task-message","@io-arc/webpack-settings","@io-arc/webpack-loaders-image"],s):s((e="undefined"!=typeof globalThis?globalThis:e||self).BuildWebpackStylus={},e.utils,e.env,e.fileList,e.TaskMessage,e.webpackSettings,e.webpackLoadersImage)}(this,(function(e,s,r,o,i,t,a){"use strict";i=i&&Object.prototype.hasOwnProperty.call(i,"default")?i.default:i;const l={loader:"css-loader",options:{url:r.USE_CSS_FILE_LOADER,sourceMap:!1,import:!0}},n=require("mini-css-extract-plugin"),c={loader:n.loader,options:{hmr:!1}},u=require("autoprefixer"),p=require("css-mqpacker"),d=[u({grid:"autoplace",flexbox:"no-2009"})];r.CSS_POSTCSS_MQ_PACKER&&d.push(p());const S={loader:"postcss-loader",options:{sourceMap:!1,plugins:()=>d}},_=[];if(r.CSS_MINIFY){const e=require("optimize-css-assets-webpack-plugin"),s=require("postcss-safe-parser");_.push(new e({cssProcessorOptions:{parser:s,discardComments:{removeAll:!0}}}))}const f=require("webpack-fix-style-only-entries"),m=require("progress-bar-webpack-plugin"),g=[],b=new s.WebpackExtends("css"),w=b.externals(),k=b.loaders();null!=k&&g.push(...k);const y=b.plugins();null!=y&&_.push(...y);const O={mode:r.NODE_ENV,context:r.WS_CSS_PATH_ABSOLUTE,watch:r.MODE_ENV===r.MODE.WATCH,entry:()=>new Promise(e=>{e(o.FileListObject(r.WS_CSS_PATH_ABSOLUTE,"styl"))}),output:{path:r.OUTPUT_CSS_PATH_ABSOLUTE},externals:w,module:{rules:[{test:/\.styl$/,exclude:/node_modules/,use:[c,l,{loader:"resolve-url-loader",options:{sourceMap:!1,keepQuery:!0}},S,{loader:"stylus-loader",options:{sourceMap:!1,"include css":!0,define:null}}]},a.ImageLoader(r.OUTPUT_CSS_ARRAY,r.OUTPUT_IMG_ARRAY,r.IS_HASH_CSS_FILE_LOADER),...g]},plugins:[new i("stylus"),new f({extensions:["styl","css"]}),new n({filename:"[name].css",chunkFilename:"[id].css"}),new m(t.progressBar("stylus")),..._],devtool:!1,cache:!0,stats:t.stats(),performance:t.performance()};e.css=O,Object.defineProperty(e,"__esModule",{value:!0})}));
